name: frontend
env:
  - key: NEXT_PUBLIC_API_URL
    value: "https://octopus-app-ct5vs.ondigitalocean.app/api"
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "8080"
  - key: NPM_CONFIG_PRODUCTION
    value: "false"
  - key: USE_NPM
    value: "true"
  - key: USE_PNPM
    value: "false"
  - key: USE_YARN
    value: "false"
build_command: chmod +x scripts/set-env.sh && scripts/set-env.sh npm install --legacy-peer-deps && scripts/set-env.sh npm run build
run_command: npm start
http_port: 8080 